backend:
  name: git-gateway
  #name: github
  #repo: drap54/ds-gitlab
  #branch: master

publish_mode: editorial_workflow  
media_folder: static/marketing/img
public_folder: /marketing/img

collections:
  - name: 'VJLP1-NoForm'
    label: 'Vera&John Template 1'
    format: 'frontmatter'
    folder: 'assets/content/landing-page/marketing/vjlp1'
    create: true
    identifier_field: "slug_name"
    slug: '{{slug}}'
    preview_path: vjlp1/{{slug}}
    show_preview_links: false
    editor:
      preview: false
    fields:
      - label: Slug
        widget: string
        name: slug_name
        required: true  
        hint: "The last segment of landing page URL (do not include folder or file extension)"
      - label: "Locale"
        name: "promo_locale"
        widget: "object"
        colapsed: true
        fields:
          - label: "Country Code"
            name: "promo_country_code"
            widget: "select"
            default: ["jp"]  
            options:
              - { label: "Japan", value: "jp" }
              - { label: "Sweden", value: "se" }
              - { label: "Germany", value: "de" }
          - label: "Language Code"
            name: "promo_language_code"
            widget: "select"
            default: ["ja"]   
            options:
              - { label: "Japanese", value: "ja" }
              - { label: "Swedish", value: "sv" }
              - { label: "German", value: "de" } 
      - label: "Promotion Banner"
        name: "promo_banner" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Title", name: "promo_title", widget: "string"}
          - {label: "Display Title", name: "promo_title_display", widget: "boolean", default: true}
          - {label: "Subtitle", name: "promo_subtitle", widget: "string", required: false}
          - {label: "Login Button", name: promo_login_button, widget: "string"}
          - {label: "Login Button Redirect URL", name: promo_login_button_redirect_url, widget: "string"}    
          - {label: "Join Button", name: promo_join_button, widget: "string"}
          - {label: "Join Button Redirect URL", name: promo_join_button_redirect_url, widget: "string"}
          - label: "Images"
            name: "promo_images"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Desktop Background", name: promo_bg_desktop, widget: image}
              - {label: "Mobile Background", name: promo_bg_mobile, widget: image}
              - {label: "Game Logo", name: promo_game_logo, widget: image, required: false}
      - label: "Promotion Steps"
        name: "promo_steps" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Step 1 Title", name: promo_step_1_title, widget: "string"}
          - {label: "Step 1 Description", name: promo_step_1_desc, widget: "string"}
          - {label: "Step 2 Title", name: promo_step_2_title, widget: "string"}
          - {label: "Step 2 Description", name: promo_step_2_desc, widget: "string"}
          - {label: "Step 3 Title", name: promo_step_3_title, widget: "string"}
          - {label: "Step 3 Description", name: promo_step_3_desc, widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}    
      - {label: Template, name: promo_template, widget: hidden, default: "VJLP1-NoForm"}

  - name: "VJLP3-NoForm"
    label: "Vera&John Template 3"
    format: 'frontmatter'
    folder: "assets/content/landing-page/marketing/vjlp3"
    create: true
    identifier_field: "slug_name"
    slug: '{{slug}}'
    preview_path: vjlp3/{{slug}}
    show_preview_links: false
    editor:
      preview: false
    fields:
      - label: Slug
        widget: string
        name: slug_name
        required: true  
        hint: "The last segment of landing page URL (do not include folder or file extension)"
      - label: "Locale"
        name: "promo_locale"
        widget: "object"
        colapsed: true
        fields:
          - label: "Country Code"
            name: "promo_country_code"
            widget: "select"
            default: ["jp"]  
            options:
              - { label: "Japan", value: "jp" }
              - { label: "Sweden", value: "se" }
              - { label: "Germany", value: "de" }
          - label: "Language Code"
            name: "promo_language_code"
            widget: "select"
            default: ["ja"]   
            options:
              - { label: "Japanese", value: "ja" }
              - { label: "Swedish", value: "sv" }
              - { label: "German", value: "de" } 
      - label: "Promotion Banner"
        name: "promo_banner" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Title", name: "promo_title", widget: "string"}
          - {label: "Display Title", name: "promo_title_display", widget: "boolean", default: true}
          - {label: "Subtitle", name: "promo_subtitle", widget: "string", required: false}
          - {label: "Login Button", name: promo_login_button, widget: "string"}   
          - {label: "Login Button Redirect URL", name: promo_login_button_redirect_url, widget: "string"}     
          - {label: "Join Button", name: promo_join_button, widget: "string"}
          - label: "Join Button Location"
            name: "promo_join_button_location"
            widget: "select"
            default: ["hidden"]
            options:
              - { label: "Upper Left", value: "upper-left" }
              - { label: "Lower Right", value: "lower-right" }
              - { label: "Hidden", value: "hidden" }
          - {label: "Join Button Redirect URL", name: promo_join_button_redirect_url, widget: "string"}    
          - label: "Images"
            name: "promo_images"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Desktop Background", name: promo_bg_desktop, widget: image}
              - {label: "Mobile Background", name: promo_bg_mobile, widget: image}
          - label: "Game Slider"
            name: "game_images"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Game Icon 1", name: game_icon_1, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_1, widget: string, required: false, default: ""}
              - {label: "Game Icon 2", name: game_icon_2, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_2, widget: string, required: false, default: ""}
              - {label: "Game Icon 3", name: game_icon_3, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_3, widget: string, required: false, default: ""}
              - {label: "Game Icon 4", name: game_icon_4, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_4, widget: string, required: false, default: ""}
              - {label: "Game Icon 5", name: game_icon_5, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_5, widget: string, required: false, default: ""}
              - {label: "Game Icon 6", name: game_icon_6, widget: image, required: false, default: ""}
              - {label: "Game URL", name: game_url_6, widget: string, required: false, default: ""}
      - {label: Template, name: promo_template, widget: hidden, default: "VJLP3-NoForm"}
      - {label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'ICLP1-NoForm'
    label: 'Intercasino Template 1'
    format: 'frontmatter'
    folder: 'assets/content/landing-page/marketing/iclp1'
    create: true
    identifier_field: "promo_banner.promo_title"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: iclp1/{{slug}}
    show_preview_links: false
    editor:
      preview: false
    fields:
      - label: "Locale"
        name: "promo_locale"
        widget: "object"
        colapsed: true
        fields:
          - label: "Country Code"
            name: "promo_country_code"
            widget: "select"
            default: ["jp"]  
            options:
              - { label: "Japan", value: "jp" }
              - { label: "Sweden", value: "se" }
              - { label: "Germany", value: "de" }
          - label: "Language Code"
            name: "promo_language_code"
            widget: "select"
            default: ["ja"]   
            options:
              - { label: "Japanese", value: "ja" }
              - { label: "Swedish", value: "sv" }
              - { label: "German", value: "de" } 
      - label: "Promotion Banner"
        name: "promo_banner" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Title", name: "promo_title", widget: "string"}
          - {label: "Login Button Text", name: promo_login_button_text, widget: "string"}
          - {label: "Login Button Redirect URL", name: promo_login_button_redirect_url, widget: "string"}
          - {label: "Subtitle 1", name: "promo_subtitle_1", widget: "string", required: false}
          - {label: "Main Heading H1", name: "promo_main_heading", widget: "string", required: false}
          - {label: "Animate Heading", name: "promo_title_animate", widget: "boolean", default: true}
          - {label: "Subtitle 2", name: "promo_subtitle_2", widget: "string", required: false}
          - {label: "Signup Button Text", name: promo_signup_button, widget: "string"}
          - {label: "Signup Button Redirect URL", name: promo_signup_button_redirect_url, widget: "string"}    
          - {label: "Small Term Text Link", name: promo_smallterm_text_link, widget: "string"}
          - {label: "Small Term Redirect URL", name: promo_smallterm_redirect_url, widget: "string"}
          - {label: "Small Term Text", name: promo_smallterm_text, widget: "string"}
          - label: "Images"
            name: "promo_images"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Desktop Background", name: promo_bg_desktop, widget: image}
              - {label: "Mobile Background", name: promo_bg_mobile, widget: image}
              - {label: "Game Logo", name: promo_game_logo, widget: image, required: false}
      - label: "Promotion Steps"
        name: "promo_steps" 
        widget: "object"
        collapsed: true
        fields:
          - {label: "Step 1 Title", name: promo_step_1_title, widget: "string"}
          - {label: "Step 1 Description", name: promo_step_1_desc, widget: "string"}
          - {label: "Step 2 Title", name: promo_step_2_title, widget: "string"}
          - {label: "Step 2 Description", name: promo_step_2_desc, widget: "string"}
          - {label: "Step 3 Title", name: promo_step_3_title, widget: "string"}
          - {label: "Step 3 Description", name: promo_step_3_desc, widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}    
      - {label: Template, name: promo_template, widget: hidden, default: "VJLP1-NoForm"}      

  - label: "Vera&John Homepage"
    name: "VJ-Homepage"
    format: 'frontmatter'
    show_preview_links: false
    editor:
      preview: false
    files:
      - label: "Vera&John Homepage"
        name: "VJ-Homepage"
        file: "assets/content/landing-page/marketing/vjhp/vera-john-homepage.md"
        fields:
          - label: "Vera&John Homepage"
            name: "promo_banner"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Title for this edit", name: "promo_title", widget: "string"}
          - label: "Login Header Section"
            name: "login_header_section"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Login Header Text", name: login_header_text, widget: "string"}
              - {label: "Login Header Redirect URL", name: login_header_redirect_url, widget: "string"}
          - label: "Header Section"
            name: "header_section"
            widget: "object"
            collapsed: true
            fields:
              - {label: "Header Button Text", name: header_text, widget: "string"}
              - {label: "Header Button Redirect URL", name: header_button_redirect_url, widget: "string"}
              - {label: "Login Account Text", name: header_login_account_text, widget: "string"}
              - {label: "Login Account Text Redirect URL", name: header_login_account_text_redirect_url, widget: "string"}
          - label: "Games Brick Section"
            name: "games_brick_section" 
            widget: "object"
            collapsed: true
            fields:
              - label: "Column 1"
                name: "games_brick_column_1"
                widget: "object"
                colapsed: true
                fields:
                  - {label: "Button", name: games_brick_column_1_button, widget: "string"}   
                  - {label: "Button Redirect URL", name: games_brick_column_1_button_redirect_url, widget: "string"} 
              - label: "Column 2"
                name: "games_brick_column_2"
                widget: "object"
                colapsed: true
                fields:
                  - {label: "Button", name: games_brick_column_2_button, widget: "string"}   
                  - {label: "Button Redirect URL", name: games_brick_column_2_button_redirect_url, widget: "string"}
          - label: "Testimonials Section"
            name: "testimonials_section"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Button Text", name: testimonials_button_text, widget: "string"}   
              - {label: "Button Redirect URL", name: testimonials_button_redirect_url, widget: "string"}
          - label: "Footer Section"
            name: "footer_section"
            widget: "object"
            colapsed: true
            fields:
              - {label: "Menu 1", name: footer_menu_1_text, widget: "string"}   
              - {label: "Menu 1 Redirect URL", name: footer_menu_1_redirect_url, widget: "string"}
              - {label: "Menu 2", name: footer_menu_2_text, widget: "string"}   
              - {label: "Menu 2 Redirect URL", name: footer_menu_2_redirect_url, widget: "string"}
              - {label: "Menu 3", name: footer_menu_3_text, widget: "string"}   
              - {label: "Menu 3 Redirect URL", name: footer_menu_3_redirect_url, widget: "string"}
              - {label: "Menu 4", name: footer_menu_4_text, widget: "string"}   
              - {label: "Menu 4 Redirect URL", name: footer_menu_4_redirect_url, widget: "string"}